const collections = [
  "Artisan Bricks",
  "Astral Shards",
  "B-Day Candles",
  "Berry Boxes",
  "Big Years",
  "Bling Binkies",
  "Bonded Rings",
  "Bow Ties",
  "Bunny Muffins",
  "Candy Canes",
  "Clover Pins",
  "Cookie Hearts",
  "Crystal Balls",
  "Cupid Charms",
  "Desk Calendars",
  "Diamond Rings",
  "Durov's Caps",
  "Easter Eggs",
  "Electric Skulls",
  "Eternal Candles",
  "Eternal Roses",
  "Evil Eyes",
  "Faith Amulets",
  "Flying Brooms",
  "Fresh Socks",
  "Gem Signets",
  "Genie Lamps",
  "Ginger Cookies",
  "Hanging Stars",
  "Happy Brownies",
  "Heart Lockets",
  "Heroic Helmets",
  "Hex Pots",
  "Holiday Drinks",
  "Homemade Cakes",
  "Hypno Lollipops",
  "Ice Creams",
  "Input Keys",
  "Instant Ramens",
  "Ion Gems",
  "Ionic Dryers",
  "Jacks-in-the-Box",
  "Jelly Bunnies",
  "Jester Hats",
  "Jingle Bells",
  "Jolly Chimps",
  "Joyful Bundles",
  "Khabib's Papakhas",
  "Kissed Frogs",
  "Light Swords",
  "Lol Pops",
  "Loot Bags",
  "Love Candles",
  "Love Potions",
  "Low Riders",
  "Lunar Snakes",
  "Lush Bouquets",
  "Mad Pumpkins",
  "Magic Potions",
  "Mighty Arms",
  "Mini Oscars",
  "Money Pots",
  "Moon Pendants",
  "Mousse Cakes",
  "Nail Bracelets",
  "Neko Helmets",
  "Party Sparklers",
  "Perfume Bottles",
  "Pet Snakes",
  "Plush Pepes",
  "Precious Peaches",
  "Pretty Posies",
  "Rare Birds",
  "Record Players",
  "Restless Jars",
  "Sakura Flowers",
  "Santa Hats",
  "Scared Cats",
  "Sharp Tongues",
  "Signet Rings",
  "Skull Flowers",
  "Sky Stilettos",
  "Sleigh Bells",
  "Snake Boxes",
  "Snoop Cigars",
  "Snoop Doggs",
  "Snow Globes",
  "Snow Mittens",
  "Spiced Wines",
  "Spring Baskets",
  "Spy Agarics",
  "Star Notepads",
  "Stellar Rockets",
  "Swag Bags",
  "Swiss Watches",
  "Tama Gadgets",
  "Top Hats",
  "Toy Bears",
  "Trapped Hearts",
  "UFC Strikes",
  "Valentine Boxes",
  "Victory Medals",
  "Vintage Cigars",
  "Voodoo Dolls",
  "Westside Signs",
  "Whip Cupcakes",
  "Winter Wreaths",
  "Witch Hats",
  "Xmas Stockings"
]

const artisanBricks = [
  "Delicate Wash",
  "Foosball",
  "Chocolate",
  "Sardines",
  "Concrete",
  "Sandstone",
  "Domino",
  "Switch",
  "Silver",
  "Cheesecake",
  "Oranges",
  "Big Cubus",
  "Toxic Ooze",
  "Molten Core",
  "Art Nouveau",
  "Floppa Plush",
  "Game Console",
  "Harlequin",
  "Keyboard",
  "Red Caviar",
  "VHS Tape",
  "Firestarter",
  "Ghost Trap",
  "Luggage",
  "Safe Box",
  "Retro Player",
  "Mimic Chest",
  "Watermelon",
  "Buzzy Bee",
  "Fight Club",
  "Nuclear Waste",
  "TON Ledger",
  "El Dorado",
  "Pro Gamer",
  "Pyramid",
  "Diamond",
  "Duck Bath",
  "Emerald",
  "Ice Mammoth",
  "Chessboard",
  "Fashion Bag",
  "Infinity Box",
  "Bomb Planted",
  "Escher’s Cube",
  "Pearl",
  "Poker Chips",
  "Cash Roll",
  "Cherry Ruby",
  "Grand Piano",
  "Grass Block",
  "Gemstones",
  "Treasure",
  "Fifth Element",
  "Scorpion",
  "Brick 3310",
  "Jewelry Box",
  "Oriental",
  "Gold Bar",
  "USBrick",
  "Gold Block"
];

const astralShards = [
  "Gold 999",
  "Bouquet",
  "Emerald",
  "Sapphire",
  "Galactite",
  "Aquamarine",
  "Spinel",
  "Amethyst",
  "Ocean Jasper",
  "Sunstone",
  "Garnet",
  "Ethereal",
  "Glowstone",
  "Gramite",
  "Citrine",
  "Crystal Punk",
  "Moonstone",
  "Silver Art",
  "Tanzanite",
  "True Opal",
  "Labradorite",
  "Moonlit",
  "Red Ruby",
  "Ruby Fuchsite",
  "Black Diamond",
  "Barbed",
  "Nouveau Gold",
  "Uranium",
  "Ivy Vine",
  "Bogartite",
  "Ammolite",
  "Candy Flossite",
  "RGB-ite",
  "Tourmaline",
  "Fractured",
  "Warholite",
  "Jurassic",
  "White Opal",
  "Aquarium",
  "Arctite",
  "Excalibrite",
  "Premium",
  "Pure Silver",
  "Muffin",
  "Lovestone",
  "Nectarite",
  "Blender",
  "Dark Soul",
  "Elven Might",
  "Eve’s Apple"
];

const bDayCandles = [
  "Ice Crackle",
  "Candy Message",
  "Wee Hours",
  "Bright Side",
  "Stardust",
  "Moon Wish",
  "Sweet Glaze",
  "Best Wishes",
  "Sugar Party",
  "Summer Walk",
  "Cotton Candy",
  "Spring Meadow",
  "Be Awesome!",
  "Golden Hour",
  "Festive",
  "Tropic Dream",
  "Twilight Beam",
  "Winter Noon",
  "Icicle",
  "Golden Age",
  "Blue Caramel",
  "Eternal Glow",
  "Shine Bright",
  "Cheers",
  "Confetti",
  "Pear Cocktail",
  "Poltergeist",
  "Wax Glow",
  "Forever Young",
  "Pop Art",
  "Wicked",
  "Citrus Candy",
  "Fresh Mint",
  "Multicolor",
  "Warm Wick",
  "Choco Wax",
  "Old Cartoon",
  "Midnight",
  "Jage Crystal",
  "Black Ink",
  "Icy Pink",
  "Silver Year",
  "Rose Mint",
  "Lolipop",
  "Tropicana",
  "Pinky Dream",
  "Bronze Age",
  "Dream Big",
  "Glittery Day",
  "Magic Powers",
  "Peachy",
  "Pop Tart",
  "Shine On",
  "Tender Flame",
  "Orange Mood",
  "Pastel Spark",
  "Happy Flame",
  "Starry Night",
  "Anniversary",
  "Steel Strong",
  "Juicy Ginger",
  "Rainbow",
  "Wait a Minute",
  "Jelly Desert",
  "Princess",
  "Red Ribbon",
  "Valentine",
  "Superstar",
  "Stay Cool",
  "Forecast",
  "Firecracker",
  "Neon Lights",
  "Jelly Bubble",
  "Sparkler",
  "Party Hard",
  "Broadway",
  "Crazy Frog",
  "Donut Cream",
  "Mouse Brunch",
  "You Rock!",
  "Festive Day",
  "Glitch",
  "Neon Sign",
  "Backyard",
  "Payday",
  "Duck Attack",
  "Melted Butter",
  "On Fire",
  "Winter Fun",
  "Cherrific",
  "Pixel Wish",
  "Purr Magic",
  "Small Gifts",
  "Crunchy",
  "Eggcellent",
  "Bubbly",
  "Happy Meows",
  "Shocker",
  "Kaboom!",
  "Final Boss"
];

const berryBoxes = [
  "Golden Dip",
  "Manga",
  "Valentine",
  "Alpha",
  "Iridescent",
  "Canis Major",
  "Rawberry",
  "Milky Cows",
  "Sweet Game",
  "Comic Book",
  "Foraged",
  "Baubles",
  "Lovey Dovey",
  "Starberry",
  "Frosty Icing",
  "Gryffindor",
  "Fresh",
  "Zomberry",
  "RGBerry",
  "White Cocoa",
  "Refraction",
  "Sweet Star",
  "Harlequin",
  "Luxury",
  "Ice Diamond",
  "Lemon Lime",
  "Paparazzi",
  "Martian",
  "Glimglam",
  "Spring",
  "Mood Ring",
  "Rarity",
  "Cupid",
  "Eiffel 95",
  "Noir",
  "Chillberry",
  "Lovely Bites",
  "Glitchberry",
  "Anniversary",
  "Berryllium",
  "Purple Ribbon",
  "Unicorns",
  "Atmosphere",
  "Rose Gold",
  "Ribbons",
  "Teeth Crush",
  "Anatomy",
  "Tuxedo",
  "Bowtied",
  "Kawaii",
  "Sketchy",
  "Pointilism",
  "Strobe",
  "Clarity",
  "Natural",
  "Confetti",
  "Infrared",
  "Sine Wave",
  "Wedded",
  "Bumberries",
  "High Voltage",
  "Magenta",
  "Lovestorm",
  "Art Project",
  "Extra Berry",
  "Nature Box",
  "Berrific",
  "Lady Bites",
  "Megabite",
  "Sweet Kiss"
];

const bigYears = [
  "Bitcoin",
  "Matrix",
  "YouTubes",
  "Walking Dead",
  "Pavel Durov",
  "Qing Dynasty",
  "Pokeball",
  "Cyberpunk",
  "Retrowave",
  "Periodic Table",
  "Fallout",
  "Steve Jobs",
  "Nuclein",
  "2048",
  "Night Bat",
  "Emo Music",
  "Freddy",
  "First Website",
  "Frankenstein",
  "Columbus",
  "Industrial",
  "Wizard Boy",
  "Picasso",
  "AC/DC",
  "Christmas Carol",
  "Spider Sense",
  "Gold Mine",
  "Nostradamus",
  "Van Gogh",
  "Mauveine",
  "Bikini Bottom",
  "War and Peace",
  "Einstein",
  "A New Hope",
  "Da Vinci",
  "First Flight",
  "Salvador Dali",
  "Big Brother",
  "Covid-19",
  "Telegram",
  "Original Cola",
  "Toon Family",
  "Sputnik-1",
  "Frida Kahlo",
  "Sherlock",
  "Zombie Film",
  "Cheshire Cat",
  "Sir Chaplin",
  "The Hobbit",
  "Balloons",
  "Creator",
  "Game Boy",
  "King of Pop",
  "The Nether",
  "Jelly Year"
];

const blingBinkies = [
  "Ice Pop",
  "Royal Heir",
  "Regent",
  "Bullet",
  "Crystal Sky",
  "Red Bull",
  "Water Lily",
  "Marmalade",
  "Bloodsucker",
  "Illuminati",
  "Crystal Wings",
  "Gem Seeker",
  "Irish Kiss",
  "Abyss Binky",
  "Shellfish",
  "Violetta",
  "Baby Lou",
  "Event Horizon",
  "Clown",
  "Rancho",
  "Soccer",
  "Cthulhu",
  "Grizzly Bear",
  "Void Watcher",
  "Black Metal",
  "Biscuit",
  "Ice Queen",
  "Shiny Armor",
  "Toxic Slime",
  "Brass Knuckles",
  "Christmas",
  "Victorian",
  "Adult Toy",
  "Danger Bot",
  "Light Bulb",
  "Leopard",
  "The Ankh",
  "First Ax",
  "Tribal Skull",
  "Cubic",
  "Poison Apple",
  "Silver Spoon",
  "Peach Flower",
  "Diamond",
  "Metal Chain",
  "Star Fighter",
  "Cupid Ruby",
  "Monarch",
  "Night Bat",
  "Red Lipstick"
];

const bondedRings = [
  "Love Whisper",
  "Spectrum",
  "Bloody Mary",
  "Black Hole",
  "Frostband",
  "Line Art",
  "Lime Factory",
  "Yin Yang",
  "Miami Art",
  "Leopard",
  "Atomic Core",
  "Rainbow Halo",
  "Eclipse",
  "Duo Vision",
  "Space Inside",
  "Golden Star",
  "Dalmatian",
  "Kraken’s Grip",
  "Neo Tribe",
  "Solid Magma",
  "Zebra",
  "Duckling",
  "Pixel Loot",
  "Cheese",
  "Neon Pulse",
  "Anaconda",
  "Cat Bed",
  "Ironwood",
  "Runewood",
  "Hot Wheel",
  "Rainbow",
  "Froge Ring",
  "Tiger Amulet",
  "Magic Runes",
  "Astro Silver",
  "Moon Dust",
  "Thunder Bolt",
  "Soap Bubbles",
  "Fireball",
  "Hamster Wheel",
  "Stratosphere",
  "Mouse Wheel",
  "Hourglass",
  "Metal Forever",
  "Highway",
  "Spatial Grid",
  "Neo Matrix",
  "Ring of Roots",
  "Asteroid",
  "Goldsmith"
];

const bowTies = [
  "Bordeaux",
  "Football",
  "Classic",
  "Red Rose",
  "Cupid’s Bow",
  "Billiards",
  "Utyan",
  "The Raven",
  "Cherries",
  "Dribble",
  "Irish Knot",
  "Eggplants",
  "Blue Morpho",
  "Ladybug",
  "Chebu",
  "Gamepad",
  "Modern Art",
  "Tortuga",
  "Bumblebee",
  "Canada",
  "Strawberry",
  "Volleyball",
  "Creator",
  "Sailor Moon",
  "Squid Tie",
  "Mistletoe",
  "Spider Sense",
  "Elephant",
  "Mondrian",
  "The Lion",
  "Union Jack",
  "The Serpent",
  "The Badger",
  "Durov’s Dog",
  "Bus Guys",
  "Despicable",
  "Vampire",
  "Baby Yoda",
  "Doge Gem",
  "Dracarys",
  "Dark Lord",
  "Velvet Gold",
  "Batwing",
  "Heritage",
  "Singularity",
  "Firefly",
  "Farfalle",
  "Prism",
  "Tie Fighter",
  "Cambridge"
];

const bunnyMuffins = [
  "Silent Film",
  "Photonegative",
  "Classic",
  "Red Alert",
  "Wolverine",
  "Space Drive",
  "Cappuccino",
  "Old Batman",
  "Apple Fresh",
  "Jellyfish",
  "Softness",
  "Berry Punch",
  "Latte",
  "Matcha",
  "Chocolate",
  "Spiderman",
  "Clear Sky",
  "Cloud",
  "Orange Bliss",
  "Valentine",
  "Lava Cake",
  "Refreshing",
  "Key Lime",
  "Berry Jam",
  "Sour Drop",
  "Сhamomile",
  "Dragon Fruit",
  "Juicy Melon",
  "Little Sister",
  "Sweet Grape",
  "Droplet",
  "Grapefruit",
  "Hulk",
  "Young Chili",
  "Chill-Out",
  "Opera Ghost",
  "Bubble Gum",
  "Velvet Rose",
  "Mandarin",
  "Shiba Inu",
  "Eclair",
  "Slime",
  "Vanilla",
  "Cotton Candy",
  "Gorgeous",
  "Silver",
  "Blueberry",
  "Dark Cherry",
  "Dreamer",
  "Sea Cruise",
  "Tiffani",
  "Brave Tiger",
  "Butterfly Tie",
  "Citrus Boom",
  "Macaron",
  "Sour Apple",
  "Girlfriend",
  "Gold",
  "Iceberry",
  "Cornflower",
  "Cutie",
  "Green Tea",
  "Lavender Kiss",
  "Citrus",
  "Orchid",
  "Berry Tale",
  "Lollipop",
  "Froggy",
  "Watermelon",
  "Electric",
  "Grandma’s Pie",
  "Sugar Glade",
  "Winter Dessert",
  "Diamond",
  "Cookie Bun",
  "Choco Bear",
  "Day and Night",
  "Pink Bow",
  "Sunshine",
  "Bronze",
  "Hackathon",
  "Snowman",
  "Telegram",
  "Ice Cream",
  "Gothic",
  "Lu Crystal",
  "Meow Meow",
  "Frosted",
  "Party Time",
  "Sweet Miracle",
  "Lovely Ruby",
  "Mr. Souffle",
  "Neon Sign",
  "Airy Souffle",
  "Honey Bee",
  "Party Clown",
  "Mermaid",
  "Unicorn",
  "Meltdown",
  "With Love"
];

const candyCanes = [
  "Negativus",
  "Joker",
  "Pink Mango",
  "Bronzy",
  "Golden Jelly",
  "Silver Frost",
  "Tropico",
  "Starry Cane",
  "Diggory",
  "Toxicane",
  "Colorfunk",
  "Phoenix",
  "Polka Pop",
  "Iceblink",
  "Phantom",
  "Amber Glitter",
  "Blue Bliss",
  "Minty Mirth",
  "Lovely Kiss",
  "Lime Twist",
  "Violet Berry",
  "New Layer",
  "Nightmare",
  "Cherry Charm",
  "Sweet Deal",
  "Final Offer",
  "Peppy Pink",
  "Grinch",
  "Angelius",
  "Sugar Crush",
  "Lovegood",
  "Demonius",
  "Lazy Nap",
  "Argento",
  "Goldium",
  "Hologlow",
  "Neon Wave",
  "Old School",
  "Sticky Sweet",
  "Honeycomb",
  "Masterpiece",
  "Toxic Treat",
  "Short Circuit",
  "Designer",
  "Hex Pot",
  "Discount",
  "Oblina",
  "Malfoy",
  "Weasley",
  "Mythic Candy"
];

const cloverPins = [
  "Sell High",
  "Buy Low",
  "Matrix",
  "Verdant Plaid",
  "Celtic Knot",
  "Nebula",
  "Peacock",
  "Fortune Meter",
  "Cheese",
  "Red Tartan",
  "Good Boy",
  "Golden Ticket",
  "Top Student",
  "Maple Leaf",
  "Four Wishes",
  "Glass Rainbow",
  "Purrfect Paw",
  "Ruby Clover",
  "Vinyl Record",
  "Watermelon",
  "Fabulous",
  "Butterfly",
  "Hot Brand",
  "Crystal Hearts",
  "Kaleidoscope",
  "Joystick",
  "Ice Cream",
  "Stained Glass",
  "Fortune Cookie",
  "Orange Juice",
  "Needlework",
  "Sangria",
  "Lollipop",
  "Pepperoni",
  "Star Princess",
  "Balloon",
  "Rose Quartz",
  "Golden Ale",
  "Pinwheel",
  "Frutiger Aero",
  "Berry Waffle",
  "Soap Bubbles",
  "Corrupted",
  "Lava Lamp",
  "Merrow",
  "Kelly Green",
  "Moon Power",
  "Sakura",
  "Tama Gadget",
  "Emo Pin"
];

const cookieHearts = [
  "Telecake",
  "Baked Logo",
  "Druid Snack",
  "Midsummer",
  "Grinch",
  "Hearth",
  "Winterfell",
  "Chilled",
  "Mint Cream",
  "Sunlight",
  "Spicy Maple",
  "Dark Rainbow",
  "Elven Bakery",
  "Meadow",
  "Citrus Glaze",
  "Vanilla",
  "Toffee",
  "Black Heart",
  "Schnecken",
  "Red Blues",
  "Oatmeal Star",
  "The Circle",
  "Silver",
  "Red Velvet",
  "Cheesecake",
  "Crayola",
  "Broken Code",
  "Changeling",
  "Kawaii Frog",
  "Rainbow",
  "Ultra Pink",
  "Rosaria",
  "Manga",
  "Pink Yogurt",
  "Cold Mint",
  "Late Fall",
  "The Star",
  "Fly Agaric",
  "Liquorice",
  "Red Apple",
  "The Triangle",
  "Infinity Gems",
  "Sprinkles",
  "Carefree",
  "Ice Rink",
  "Doughnut",
  "Fried Egg",
  "The Umbrella",
  "Nyam Cat",
  "Squid",
  "Fairy Lights",
  "Honeymoon",
  "Neon Candy",
  "Medovik",
  "Toasted",
  "Rubycake",
  "Graveyard",
  "Choco Crunch",
  "Fairy Tale",
  "Choco Chips",
  "Energy Bar",
  "For You",
  "Strawberry",
  "Choco Fudge",
  "Shiny Gem",
  "Caramel Bow",
  "Kawaii Bunny",
  "Watermelon",
  "Valentine",
  "Hearty Crust",
  "First Crush",
  "Gold Bar",
  "Wink Wink",
  "Pixel Beat",
  "Affection",
  "Mermaid",
  "Blueberry",
  "Soap Opera",
  "Last Bites",
  "Little Daisies",
  "Diamond",
  "Stardust",
  "Nightmare",
  "Love Story",
  "Cupid’s Arrow",
  "Baking Hot",
  "Little Star",
  "Lattice Pie",
  "Strawberry",
  "Angry Ghost",
  "Ma Chérie",
  "Cold Heart",
  "Yamete Kudasai",
  "Dark Pawder",
  "Red Rose",
  "Sugar Kitty",
  "Spades",
  "Bloodlust",
  "Lucky Charm",
  "Superstar"
];

const crystalBalls = [
  "Ghosted",
  "Prophet",
  "Brain Freeze",
  "Fuschia",
  "Peridot",
  "Lady Death",
  "Death Wish",
  "Seeing Red",
  "Deathquik",
  "Futuristic",
  "Silver",
  "Warlock",
  "Fatal Error",
  "Martian",
  "Red Skull",
  "Refreshing",
  "Cartoon",
  "Opacity",
  "Fortune",
  "Warhol",
  "Electric Shock",
  "Teddy Bear",
  "Tim Burton",
  "Frankenstein",
  "Crash Test",
  "Inkwell",
  "Pink Chess",
  "Rainbow",
  "Vitamin C",
  "Amanita",
  "Past Tell",
  "Spice Storm",
  "Hot Head",
  "Poor Kitty",
  "Billiard",
  "Pink Panther",
  "Incubus",
  "World Cup",
  "Skullberry",
  "Original Sin",
  "Daisy",
  "Samhain",
  "Baller",
  "Bozo Clown",
  "Nebula",
  "Oculus",
  "Sanguine",
  "The Lich King",
  "The Seeker",
  "Disco",
  "Wednesday",
  "Broken Heart",
  "Honey Cake",
  "Druid Circle",
  "Femme Fatale"
];

const cupidCharms = [
  "Gemstones",
  "Pink Glass",
  "Bubbles",
  "Golden Grasp",
  "Snow Queen",
  "Obsidian",
  "Lindon",
  "Starlight",
  "Glamour",
  "Ruby Red",
  "Soft Touch",
  "Vault",
  "Pink Zebra",
  "Azure Gem",
  "Lorien",
  "White Claws",
  "Emerald",
  "Pepe Love",
  "Blood Gem",
  "Cheetah",
  "Purple Glow",
  "Ruby Whisper",
  "Broken Heart",
  "Burning Love",
  "Lockpicking",
  "Web Locket",
  "Filigree",
  "Gift Wrap",
  "Cupid Pay",
  "Ribbons",
  "Padlock",
  "Crystal Clear",
  "Cursed Room",
  "Surgery",
  "Comics",
  "Moulin Rouge",
  "Blossom",
  "Mistress",
  "Golden Lace",
  "Jewels",
  "Puzzle",
  "Gothic Core",
  "Titanic",
  "Faerie",
  "Sorceress",
  "Cogwheel",
  "Ice Glass",
  "Moon Prism",
  "Antique",
  "Dryad Heart"
];

const symbol = [
  "Inguz Rune", "Trophy", "Celtic Wolf", "Alkonost", "Calm Wolf", "Fehu Rune",
  "Hand of God", "Phoenix", "Spirit Impala", "Eikthyrnir", "Mayan Moth",
  "Nordic Wolf", "Cocktail", "Kitsune", "Knight", "Money Bag", "Mountain Goat",
  "Rhino Warrior", "Coin Purse", "Eagle", "Ink Pen", "Mask", "Owl", "Wolf Rage",
  "Bastet", "Champagne", "Coat of Arms", "Diamond", "Moon Cross", "Unicorn Head",
  "Gem", "Mafdet", "Royal Crown", "Sumerian Bird", "Tribal Shield", "Venetian Mask",
  "Firebird", "Mountain Lion", "Shield", "Sparks", "Lion Head", "Okami Wolf",
  "Pyramid", "Scarab", "Bull of Heaven", "Flower Cross", "Lion King", "Scorpion",
  "Tie", "Top Hat", "Arabian Horse", "Cash", "Cobra", "Crown", "Moon Eagle",
  "Pearl", "Star", "Baphomet", "Car", "Crusader", "Dice", "Moon", "Genie Lamp",
  "Wreath", "Golden Scarab", "High Heels", "Rook", "Totem Bear", "White Deer",
  "Celtic Cross", "Fenrir", "The Eye", "Cicada", "Glasses", "Pegasus",
  "Piggy Bank", "Ram of Amun", "Ring", "Sun Lion", "Inca Sun", "Anchor",
  "Bishop", "Doberman", "Fleur-de-lis", "Coin", "Fish Skeleton", "Illuminati",
  "Koala", "Mannaz Rune", "Sakura", "Yogi Shaman", "Chest", "Oxen of Fire",
  "Sun Mountain", "Jumbo Pencil", "Sauron", "Spanner", "Coffee Bean",
  "Crystal Ball", "Hamburger", "Melon", "Axe", "Bubble Tea", "Coconut", "Gold",
  "Hippo", "Lemon", "Ouroboros", "Shark Knife", "Smartphone", "Tree of Life",
  "Viking", "Apple", "Cap", "Dessert", "Gear", "Grape", "Jellyfish", "Leaf",
  "Monstera", "Musical Note", "Pineapple", "Plume", "Sea Jelly", "Turkey",
  "Birthday Cake", "Bottlenose", "Bow Tie", "Cat Mask", "Chili", "Crab", "Fire",
  "Fish", "Garden Pot", "Grenade", "Maple Leaf", "Oak Leaf", "Pomegranate",
  "Turtle", "Twin Peaks", "Alarm", "Bell Pepper", "Blood Drop", "Bunny", "Cheese",
  "Flamingo", "Flashlight", "Flipper", "Flower", "Flower Tulip", "Hedgehog",
  "Lily", "Paw", "Pizza Slice", "Rain Drop", "Skull", "Sprout", "Star Crown",
  "Tooth", "Vortex", "Wasp", "Bone", "Gift Box", "Hammerhead", "Heart",
  "Lovely Kiss", "Manta Ray", "Narcissus", "Octopus", "Palette", "Pickaxe",
  "Scissors", "Spider Web", "Sun", "Sword", "Toilet", "Acorn", "Bandage",
  "Beetle", "Clubs", "Croissant", "Key", "Light Bulb", "Mushroom", "Piñata",
  "Polar Bear", "Police Badge", "Ball", "Bottle", "Bunny Ears", "Chili Pepper",
  "Dragonfly", "Feather", "Love Letter", "Love Lock", "Bread", "Candy", "Maple"
];

const backdrop = [
  "Midnight Blue", "Silver Blue", "Persimmon", "Desert Sand", "Pure Gold",
  "Cappuccino", "Amber", "Black", "Ivory White", "Copper",
  "Dark Lilac", "Fandango", "Turquoise", "Emerald", "Pacific Green",
  "Malachite", "Roman Silver", "Strawberry", "Pacific Cyan", "Aquamarine",
  "Chestnut", "French Blue", "Mystic Pearl", "Neon Blue", "Pine Green",
  "Pistachio", "Raspberry", "Electric Indigo", "Lemongrass", "Satin Gold",
  "Battleship Grey", "Lavender", "Mint Green", "Shamrock Green", "Sky Blue",
  "Steel Grey", "Carrot Juice", "Cyberpunk", "Hunter Green", "Moonstone",
  "Orange", "Electric Purple", "Jade Green", "English Violet", "Grape",
  "Burgundy", "Indigo Dye", "Purple", "Cobalt Blue", "Onyx Black",
  "Coral Red", "Khaki Green", "Rosewood", "Light Olive", "Navy Blue",
  "Azure Blue", "Caramel", "Chocolate", "Sapphire", "Platinum"
];