FROM node:22-alpine

RUN apk add --no-cache libc6-compat
WORKDIR /app

RUN npm i -g @nestjs/cli

COPY package.json package-lock.json ./
COPY apps/frontend/package.json ./apps/frontend/
COPY apps/backend/package.json ./apps/backend/

RUN npm ci --legacy-peer-deps

COPY . .

EXPOSE 3000
EXPOSE 3001