FROM node:22-alpine

RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package.json package-lock.json* pnpm-workspace.yaml* lerna.json* ./
COPY shared/contracts/package.json ./shared/contracts/
COPY apps/frontend/package.json ./apps/frontend/
COPY apps/backend/package.json* ./apps/backend/

RUN npm config set registry https://registry.npmmirror.com

RUN npm config set fetch-retry-maxtimeout 120000 && \
    npm config set fetch-retry-mintimeout 20000 && \
    npm config set fetch-retries 5 && \
    npm install --legacy-peer-deps

COPY . .

EXPOSE 3000